export  const cashiersData = [
        {
            name: "Volt15.cashier5",
            id: "3324",
            username: "Falco8.cashier5",
            active: "Yes",
            isSupervisor: "No",
            isfirstLogin:"No",
            cashLimit: 18000,
            cashToday: 0,
        createdAt: "2025-07-14 08:40",
            shop: "Volt15",
        },
        {
            name: "Volt15.cashier4",
            id: "3323",
            username: "Falco8.cashier4",
            active: "Yes",
            isSupervisor: "No",
            isfirstLogin:"Yes",
            cashLimit: 18000,
            cashToday: 0,
            createdAt: "2025-07-14 08:40",
            shop: "Volt15",
        },
        {
            name: "Volt15.cashier3",
            id: "3322",
            username: "Falco8.cashier3",
            active: "Yes",
            isSupervisor: "No",
            isfirstLogin:"Yes",
            cashLimit: 18000,
            cashToday: 0,
            createdAt: "2025-07-14 08:40",
            shop: "Volt15",
        },
        {
            name: "Volt15.cashier2",
            id: "3321",
            username: "Falco8.cashier2",
            active: "Yes",
            isSupervisor: "No",
            isfirstLogin:"Yes",
            cashLimit: 18000,
            cashToday: -448,
            createdAt: "2025-07-14 08:40",
            shop: "Volt15",
        },
        {
            name: "Volt15.cashier1",
            id: "3320",
            username: "Falco8.cashier1",
            active: "Yes",
            isSupervisor: "Yes",
            isfirstLogin:"Yes",
            cashLimit: 18000,
            cashToday: 3781,
            createdAt: "2025-07-14 08:40",
             shop: "Volt15",
        },
        {
            name: "Volt14.cashier5",
            id: "3306",
            username: "Falco7.cashier5",
            active: "Yes",
            isSupervisor: "No",
            isfirstLogin:"No",
            cashLimit: 18000,
            cashToday: 0,
            createdAt: "2025-07-13 09:21",
             shop: "Volt15",
        },
        {
            name: "Volt12.cashier4",
            id: "3305",
            username: "Falco7.cashier4",
            active: "Yes",
            isSupervisor: "No",
            isfirstLogin:"No",
            cashLimit: 18000,
            cashToday: 0,
            createdAt: "2025-07-13 09:21",
             shop: "Volt15",
        },
    ]